### ISSUE TITLE
  mv: cannot create directory '/flu-amd/IRMA_RES/modules/zQCNwBiT5rr5T3CiVknW': Permission denied

### ISSUE THREAD

**Issue by aswarren** [DOH-JDJ0303/VAPER#7]
### Description of the bug

Trying to follow the default invocation
nextflow run -profile apptainer -r main --input ./vaper_samplesheet.csv --outdir vaper_results

Makes it to the IRMA step and I consistently get
  mv: cannot create directory '/flu-amd/IRMA_RES/modules/zQCNwBiT5rr5T3CiVknW': Permission denied

I tried to paper over it by adding a bind to the apptainer portion of the nextflow.config
runOptions = '--bind /my_accessible_dir:/flu-amd/IRMA_RES'

and then do the following on the local instance
nextflow run ./vaper -profile apptainer --input ./vaper_samplesheet.csv --outdir vaper_results  -c ./vaper/nextflow.config

but I still get the same error.

### Command used and terminal output

```console
nextflow run -profile apptainer -r main --input ./vaper_samplesheet.csv --outdir vaper_results
```

**Comment by DOH-JDJ0303** [comment]
@aswarren, this should be fixed now. Let me know if the problem persists and I will keep looking into it. Thanks!

**Comment by aswarren** [comment]
Command error:
  INFO:    gocryptfs not found, will not be able to use gocryptfs
  mv: cannot create directory '/flu-amd/IRMA_RES/modules/bQTNqegz7CyWT3JU8Dk6': Permission denied

I am still getting this error with the -latest option. Also after pulling down the latest from a local repo.
Seems to come primarily from the docker image used for docker not being writeable?
Respectively here are the two commands:

nextflow run DOH-JDJ0303/VAPER -profile apptainer -r main -latest --input ./vaper_samplesheet.csv --outdir vaper_results --max_cpus 30 --max_memory 270.GB

nextflow run ./vaper -profile apptainer --input ./vaper_samplesheet.csv --outdir vaper_results --max_cpus 30 --max_memory 270.GB

**Comment by DOH-JDJ0303** [comment]
This issue is specific to Singularity/Apptainer. I have noticed that nextflow can be a bit weird about pulling the latest updates from a repo. It may be worth cloning the repo and calling it locally. This should be less of an issue in the future when a stable version is released.

1. `git clone https://github.com/DOH-JDJ0303/vaper.git`
2. `run nextflow vaper/main.nf -profile apptainer --input vaper_samplesheet.csv --outdir vaper_results --max_cpus 30 --max_memory 270.GB`

If that doesn't work, then I will continue troubleshooting.

**Comment by DOH-JDJ0303** [comment]
Sorry, re-reading your comment and you said you tried cloning locally. Are you able to share the `.command.run` file for the failed run? It will be in the work directory for the failed process (e.g. `work/03/190460ecad572c85c11aa21eb6da49/.command.run`). It should help confirm that the changes I made were introduced.

**Comment by aswarren** [comment]
same error with: nextflow run ./vaper/main.nf -profile apptainer --input ./vaper_samplesheet.csv --outdir vaper_results --max_cpus 30 --max_memory 270.GB

git rev-parse HEAD
927edde0e6ed419f3bed94d41e43ba83b6bc2322

Find the .command.run attached.
[example.command.run.txt](https://github.com/user-attachments/files/15917968/example.command.run.txt)

**Comment by DOH-JDJ0303** [comment]
Ok, thanks! I will continue testing.

**Comment by aswarren** [comment]
Guessing here, but --writable-tmpfs wouldn't apply to 
irma_path=\$(which IRMA)

Since that is located in the staphb container straight up in /flu-amd/ or whatever.

https://github.com/DOH-JDJ0303/vaper/blob/927edde0e6ed419f3bed94d41e43ba83b6bc2322/modules/local/irma.nf#L29

**Comment by DOH-JDJ0303** [comment]
Ok. I think I came up with a solution that should be compatible with Singularity/Apptainer. Let me know if the issue still persists.
